server:
  port: 8003
spring:
  application:
    name: service-vod

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 112.125.88.235:8848
aliyun:
  vod:
    file:
      keyid: LTAI5t6vH691eRBEZj1girmU
      keySecret: oLan1Uvx2VfUHADijkLqTMYPwRPAq6

