server:
  port: 8005
spring:
  application:
    name: service-msm

  profiles:
    active: dev

aliyun:
  vod:
    file:
      keyid: LTAI5t6vH691eRBEZj1girmU
      keySecret: oLan1Uvx2VfUHADijkLqTMYPwRPAq6
