server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev

aliyun:
  oss:
    file:
#      低于节点
      endpoint: 地域节点
      keyid: 你的访问ID
      keysecret: 访问密钥
#      bucket可以在控制台创建，也可以通过代码创建
      bucketname: bucket名称

